SLStudio.Utils.RemoveHighlighting(get_param('pitchShift', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_pitchShift', 'handle'));
annotate_port('gm_pitchShift/pitchShift/mod_by_constant', 1, 1, '');
annotate_port('pitchShift/pitchShift/Modulo by Constant HDL Optimized', 1, 1, '');
annotate_port('gm_pitchShift/pitchShift/Modulo by Constant HDL Optimized', 1, 1, '');
annotate_port('pitchShift/pitchShift/Modulo by Constant HDL Optimized', 1, 1, '');
annotate_port('gm_pitchShift/pitchShift/mod_by_constant', 1, 1, '');
annotate_port('pitchShift/pitchShift/Modulo by Constant HDL Optimized1', 1, 1, '');
annotate_port('gm_pitchShift/pitchShift/Modulo by Constant HDL Optimized1', 1, 1, '');
annotate_port('pitchShift/pitchShift/Modulo by Constant HDL Optimized1', 1, 1, '');
annotate_port('gm_pitchShift/pitchShift/mod_by_constant', 1, 1, '');
annotate_port('pitchShift/pitchShift/Modulo by Constant HDL Optimized2', 1, 1, '');
annotate_port('gm_pitchShift/pitchShift/Modulo by Constant HDL Optimized2', 1, 1, '');
annotate_port('pitchShift/pitchShift/Modulo by Constant HDL Optimized2', 1, 1, '');
annotate_port('gm_pitchShift/pitchShift/ringbuffer1', 1, 1, '');
annotate_port('pitchShift/pitchShift/ringbuffer1', 1, 1, '');
annotate_port('gm_pitchShift/pitchShift/ringbuffer1', 1, 1, '');
annotate_port('pitchShift/pitchShift/ringbuffer1', 1, 1, '');
annotate_port('gm_pitchShift/pitchShift/ringbuffer2', 1, 1, '');
annotate_port('pitchShift/pitchShift/ringbuffer2', 1, 1, '');
annotate_port('gm_pitchShift/pitchShift/ringbuffer2', 1, 1, '');
annotate_port('pitchShift/pitchShift/ringbuffer2', 1, 1, '');
