open_system('pitchShift');
open_system('gm_pitchShift');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pitchShift/pitchShift/mod_by_constant', 'user2');
annotate_port('gm_pitchShift/pitchShift/mod_by_constant', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('pitchShift/pitchShift/Modulo by Constant HDL Optimized', 'user2');
annotate_port('pitchShift/pitchShift/Modulo by Constant HDL Optimized', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pitchShift/pitchShift/Modulo by Constant HDL Optimized', 'user2');
annotate_port('gm_pitchShift/pitchShift/Modulo by Constant HDL Optimized', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('pitchShift/pitchShift/Modulo by Constant HDL Optimized', 'user2');
annotate_port('pitchShift/pitchShift/Modulo by Constant HDL Optimized', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pitchShift/pitchShift/mod_by_constant', 'user2');
annotate_port('gm_pitchShift/pitchShift/mod_by_constant', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('pitchShift/pitchShift/Modulo by Constant HDL Optimized1', 'user2');
annotate_port('pitchShift/pitchShift/Modulo by Constant HDL Optimized1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pitchShift/pitchShift/Modulo by Constant HDL Optimized1', 'user2');
annotate_port('gm_pitchShift/pitchShift/Modulo by Constant HDL Optimized1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('pitchShift/pitchShift/Modulo by Constant HDL Optimized1', 'user2');
annotate_port('pitchShift/pitchShift/Modulo by Constant HDL Optimized1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pitchShift/pitchShift/mod_by_constant', 'user2');
annotate_port('gm_pitchShift/pitchShift/mod_by_constant', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('pitchShift/pitchShift/Modulo by Constant HDL Optimized2', 'user2');
annotate_port('pitchShift/pitchShift/Modulo by Constant HDL Optimized2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pitchShift/pitchShift/Modulo by Constant HDL Optimized2', 'user2');
annotate_port('gm_pitchShift/pitchShift/Modulo by Constant HDL Optimized2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('pitchShift/pitchShift/Modulo by Constant HDL Optimized2', 'user2');
annotate_port('pitchShift/pitchShift/Modulo by Constant HDL Optimized2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pitchShift/pitchShift/ringbuffer1', 'user2');
annotate_port('gm_pitchShift/pitchShift/ringbuffer1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('pitchShift/pitchShift/ringbuffer1', 'user2');
annotate_port('pitchShift/pitchShift/ringbuffer1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pitchShift/pitchShift/ringbuffer1', 'user2');
annotate_port('gm_pitchShift/pitchShift/ringbuffer1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('pitchShift/pitchShift/ringbuffer1', 'user2');
annotate_port('pitchShift/pitchShift/ringbuffer1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pitchShift/pitchShift/ringbuffer2', 'user2');
annotate_port('gm_pitchShift/pitchShift/ringbuffer2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('pitchShift/pitchShift/ringbuffer2', 'user2');
annotate_port('pitchShift/pitchShift/ringbuffer2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pitchShift/pitchShift/ringbuffer2', 'user2');
annotate_port('gm_pitchShift/pitchShift/ringbuffer2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('pitchShift/pitchShift/ringbuffer2', 'user2');
annotate_port('pitchShift/pitchShift/ringbuffer2', 1, 1, 'Obstacle to clock-rate pipelining');
