SLStudio.Utils.RemoveHighlighting(get_param('majorChangeShift', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_majorChangeShift', 'handle'));
annotate_port('gm_majorChangeShift/majorChangeShift/mod_by_constant', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized', 1, 1, '');
annotate_port('gm_majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized', 1, 1, '');
annotate_port('gm_majorChangeShift/majorChangeShift/mod_by_constant', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized1', 1, 1, '');
annotate_port('gm_majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized1', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized1', 1, 1, '');
annotate_port('gm_majorChangeShift/majorChangeShift/mod_by_constant', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized2', 1, 1, '');
annotate_port('gm_majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized2', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized2', 1, 1, '');
annotate_port('gm_majorChangeShift/majorChangeShift/mod_by_constant', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized4', 1, 1, '');
annotate_port('gm_majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized4', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized4', 1, 1, '');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer1', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer1', 1, 1, '');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer1', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer1', 1, 1, '');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer2', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer2', 1, 1, '');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer2', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer2', 1, 1, '');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer3', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer3', 1, 1, '');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer3', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer3', 1, 1, '');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer4', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer4', 1, 1, '');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer4', 1, 1, '');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer4', 1, 1, '');
