open_system('majorChangeShift');
open_system('gm_majorChangeShift');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/mod_by_constant', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/mod_by_constant', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized', 'user2');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized', 'user2');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/mod_by_constant', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/mod_by_constant', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized1', 'user2');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized1', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized1', 'user2');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/mod_by_constant', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/mod_by_constant', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized2', 'user2');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized2', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized2', 'user2');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/mod_by_constant', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/mod_by_constant', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized4', 'user2');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized4', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized4', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized4', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized4', 'user2');
annotate_port('majorChangeShift/majorChangeShift/Modulo by Constant HDL Optimized4', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/ringbuffer1', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/ringbuffer1', 'user2');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/ringbuffer1', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/ringbuffer1', 'user2');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/ringbuffer2', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/ringbuffer2', 'user2');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/ringbuffer2', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/ringbuffer2', 'user2');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/ringbuffer3', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/ringbuffer3', 'user2');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/ringbuffer3', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/ringbuffer3', 'user2');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/ringbuffer4', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer4', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/ringbuffer4', 'user2');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer4', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_majorChangeShift/majorChangeShift/ringbuffer4', 'user2');
annotate_port('gm_majorChangeShift/majorChangeShift/ringbuffer4', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('majorChangeShift/majorChangeShift/ringbuffer4', 'user2');
annotate_port('majorChangeShift/majorChangeShift/ringbuffer4', 1, 1, 'Obstacle to clock-rate pipelining');
